build:
  command: npm run build:pages
  output_directory: dist
  root_directory: .
  base_directory: .
  build_root_directory: .
  environment:
    NODE_VERSION: 22

# 自定义部署命令
deploy:
  command: ./cloudflare-deploy.sh

routes:
  - pattern: /assets/*
    target: file
  - pattern: /*
    target: /index.html
    status: 200 