name = "haidingzhuyan-api"
main = "src/index.ts"
compatibility_date = "2023-12-01"

# R2 存储桶配置
[[r2_buckets]]
binding = 'R2_BUCKET'
bucket_name = 'haidingzhuyan'
preview_bucket_name = 'haidingzhuyan'

# KV 命名空间配置
[[kv_namespaces]]
binding = "POSTER_METADATA"
id = "ff7c311c77854f6cad6c1dbcd550e8fd"

[site]
bucket = "./public"

# 配置环境变量
[vars]
R2_ENDPOINT = "https://2e9ce2c37b30771ddabc7503e02c4c3.r2.cloudflarestorage.com" 